# -*- coding: utf-8 -*-
"""Astar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsTLw2RPAlg2QtR3vjON5lzw1IlK0XfZ
"""

import heapq

def astar(start, goal, graph, h):
    if start not in graph or goal not in graph:
        return None, float('inf')  # invalid input

    pq = []  # priority queue: (f = g + h, g, node, path)
    heapq.heappush(pq, (h.get(start, 0), 0, start, [start]))
    best_g = {start: 0}

    all_paths = []
    while pq:
        f, g, current, path = heapq.heappop(pq)

        # if current == goal:
        #     return path, g
        if current == goal:
            all_paths.append((path, g))
            continue  # keep exploring other possible paths

        for neighbor, cost in graph.get(current, []):
            if neighbor not in path:  # prevent cycles
                g2 = g + cost
                f2 = g2 + h.get(neighbor, float('inf'))
                heapq.heappush(pq, (f2, g2, neighbor, path + [neighbor]))

        # for neighbor, cost in graph.get(current, []):
        #     g2 = g + cost
        #     if g2 < best_g.get(neighbor, float('inf')):
        #         best_g[neighbor] = g2
        #         f2 = g2 + h.get(neighbor, float('inf'))
        #         heapq.heappush(pq, (f2, g2, neighbor, path + [neighbor]))

    if all_paths:
        optimal = min(all_paths, key=lambda x: x[1])
        return all_paths, optimal
    else:
        return [], (None, float('inf'))


# ---------- Adjacency list from the image ----------
graph = {
    'A': [('B', 5), ('C', 5), ('D', 5)],
    'B': [('A', 5)],
    'C': [('A', 5), ('M', 6), ('N', 5)],
    'D': [('A', 5), ('N', 1)],
    'E': [('N', 1), ('M', 1)],
    'G': [('M', 4)],
    'M': [('C', 6), ('E', 1), ('N', 6), ('G', 4)],
    'N': [('D', 1), ('C', 5), ('E', 1), ('M', 6)]
}

# ---------- Heuristic table from the figure ----------
h = {'A': 6, 'B': 6, 'C': 3, 'D': 4,
     'E': 1, 'G': 4, 'M': 0, 'N': 2}

start = 'A'
goal = 'M'


# path, cost = astar(start, goal, graph, h)
# print("Optimal path:", path)
# print("Total cost  :", cost)
# Call the function
all_paths, (opt_path, opt_cost) = astar(start, goal, graph, h)

# Now print as per your 3 requirements:
print("1) All possible paths from source to goal with total costs:")
for path, cost in all_paths:
    print("   Path: {:<40} Cost: {}".format(" -> ".join(path), cost))

print("\n2) Optimal path among these:")
print("   Path: {} with total cost: {}".format(" -> ".join(opt_path), opt_cost))





# paths_with_costs = astar(graph, start, goal,h)

# # Print all paths
# print("All possible paths from {} to {}:".format(start, goal))
# for path, cost in paths_with_costs:
#     print("Path: {:<40} Cost: {}".format(" -> ".join(path), cost))

# # Find and print optimal path
# if paths_with_costs:
#     optimal_path = min(paths_with_costs, key=lambda x: x[1])
#     print("\nOptimal path: {} with total cost: {}".format(" -> ".join(optimal_path[0]), optimal_path[1]))
# else:
#     print("No path found from {} to {}".format(start, goal))

import heapq

def astar(start, goal, graph, h):
    if start not in graph or goal not in graph:
        return None, float('inf')  # invalid input

    pq = []  # priority queue: (f = g + h, g, node, path)
    heapq.heappush(pq, (h.get(start, 0), 0, start, [start]))
    best_g = {start: 0}

    all_paths = []
    while pq:
        f, g, current, path = heapq.heappop(pq)

        # if current == goal:
        #     return path, g
        if current == goal:
            all_paths.append((path, g))
            continue  # keep exploring other possible paths

        for neighbor, cost in graph.get(current, []):
            if neighbor not in path:  # prevent cycles
                g2 = g + cost
                f2 = g2 + h.get(neighbor, float('inf'))
                heapq.heappush(pq, (f2, g2, neighbor, path + [neighbor]))

    if all_paths:
        optimal = min(all_paths, key=lambda x: x[1])
        return all_paths, optimal
    else:
        return [], (None, float('inf'))


# ---------- Adjacency list from the image ----------
graph = {
    'A': [('B', 2), ('C', 3)],
    'B': [('A', 2), ('D', 4), ('E', 2)],
    'C': [('A', 3), ('F', 2)],
    'D': [('B', 4), ('G', 2)],
    'E': [('B', 2), ('G', 3), ('H', 4)],
    'F': [('c', 2), ('H', 3)],
    'G': [('D', 2), ('E', 3), ('I', 2)],
    'H': [('E', 4), ('F', 3), ('I', 2)],
    'I': [('G', 2), ('H', 2), ('J', 1)],
    'J': [('I', 1)]
}

# ---------- Heuristic table from the figure ----------
h = {'A': 7, 'B': 6, 'C': 6, 'D': 5,
     'E': 4, 'G': 3, 'H': 2, 'I': 1, 'J': 0}

start = 'A'
goal = 'J'

all_paths, (opt_path, opt_cost) = astar(start, goal, graph, h)

print("1) All possible paths from source to goal with total costs:")
for path, cost in all_paths:
    print("   Path: {:<40} Cost: {}".format(" -> ".join(path), cost))

print("\n2) Optimal path among these:")
print("   Path: {} with total cost: {}".format(" -> ".join(opt_path), opt_cost))