# -*- coding: utf-8 -*-
"""lab_exercise_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdaY7QVfECHDT1ATxHndgAqexxsymHjY
"""

#Write a python program to find the sum of odd and even numbers from a set of numbers.

num_list = [1,2,3,4,5,6,7,8,9]


sum_odd = 0
sum_even = 0

for i in num_list:
  if i % 2 == 0:
    sum_even += i
  else:
    sum_odd += i
print("The sum of even numbers = ",sum_even)
print("The sum of odd numbers = ",sum_odd)

#Write a python program to find the smallest number from a set of numbers.

a = [8,3,5,1,9,12]
smallest = a[0]

for val in a:
  if val < smallest:
    smallest = val

print(smallest)

#Write a python program to find the sum of all numbers between 50 and 100, which are divisible by 3 and not divisible by 5.


sum = 0
for i in range(50, 101):
  if (i % 3 == 0) and (i % 5 != 0):
    sum = sum + i

print("The sum of al numbers = ", sum)

#Write a python program to find the second highest number from a set of numbers.

numbers = [10, 5, 8, 20, 3, 15]

unique_numbers = list(set(numbers))
unique_numbers.sort(reverse=True)

if len(unique_numbers) > 1:
  second_highest = unique_numbers[1]
  print("The second highest number is=", second_highest)
else:
  print("No second highestnumber found.")

#Write a python program to find the factorial of a number using for loop.

a = int(input("Enter a number = "))

factorial = 1
if a < 0 :
  print("sorry! there is no factorial")

elif a == 0 :
  print("The factprial of 0 is 1")

else:
  for i in range(1, a+1):
    factorial = factorial*i

  print(f"The factorial of {a} is {factorial}")

#Write a python program to generate Fibonacci series.

n = int(input("Enter the number of terms: "))

a, b = 0, 1
if n <= 0 :
  print("Please enter a positive integer: ")

elif n == 1:
  print("Fibonacci series: ",a)

else:
  print("Fibonacci series: ", a, b, end=" ")
  for _ in range(n - 2):
    next_term = a+b
    print(next_term, end=" ")
    a, b = b, next_term

#Write a Python program to sum all the items in a list.
numbers = [2, 5, 8, 10, 3]

total_sum = sum(numbers)
print("The sum of all items in the list is:", total_sum)

#Write a Python program to get the largest number from a list.
numbers = [10, 25, 8, 50, 15]

largest = max(numbers)
print("The largest number in the list is:", largest)

#Write a Python program to reverse a tuple.
original_tuple = (1, 2, 3, 4, 5)

reversed_tuple = original_tuple[::-1]

print("Original Tuple:", original_tuple)
print("Reversed Tuple:", reversed_tuple)

#Write a Python program to get the 4th element from the beginning and the 4th element from the last of a tuple.
t = ("w", 3, "r", "e", "s", "o", "u", "r", "c", "e")

print(t)
print("4th elements of the beginning: ", t[3])
print("4th elements of the end: ", t[-4])

#Write a Python Program to Count Even and Odd Numbers in a list.
numbers_list = [2,5,4,8,11,13,15,20,6]

even_count = 0
odd_count = 0

for number in numbers_list:
    if number % 2 == 0:
        even_count += 1
    elif number % 2 == 1:
        odd_count += 1

print("Even numbers:", even_count)
print("Odd numbers:", odd_count)